# Generated by Django 4.2.3 on 2023-12-11 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('G2k23', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'Categories'},
        ),
    ]
