# Generated by Django 4.2.3 on 2023-12-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('G2k23', '0003_alter_category_slug_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='none', verbose_name=models.CharField(max_length=255)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(verbose_name=models.CharField(max_length=255)),
        ),
    ]
