# Generated by Django 4.2.3 on 2023-12-11 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('G2k23', '0005_alter_category_slug_alter_item_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='is_solid',
            new_name='is_sold',
        ),
    ]
